### ISSUE TITLE
human.to_str

### ISSUE THREAD

**Issue by ArtemKonshyn** [Bunlde-of-His/Homeworks#1]
https://github.com/Bunlde-of-His/Homeworks/blob/bcd9f6adf7b4c63fa6beb807b0b4ee4ae8c2f837/lesson_fiveteen_OOP/human%20and%20planet%20classes.py#L59
to_str ен треба
бо вже написан __str__, print його сам викличе

**Comment by Bunlde-of-His** [comment]
Issue was corrected
